/*
  This component is responsible for displaying the list of blog posts on the /blog route

  Notes:
  - It fetches the list of blog posts from a JSON file (blog-posts.json) generated by the build process
*/
import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { RouterModule } from '@angular/router';
import { GlossyEmailInputComponent } from '../glossy-email-input/glossy-email-input.component';

export interface BlogData {
  posts: {
    id: string;
    filename: string;
    title: string;
    dateFormatted: string;
    slug: string;
    tags: string[];
    published: boolean;
    readTime: number | null;
  }[];
}

@Component({
  selector: 'app-blog-list',
  standalone: true,
  imports: [RouterModule, CommonModule, GlossyEmailInputComponent],
  templateUrl: './blog-list.component.html',
  styleUrls: ['./blog-list.component.css']
})
export class BlogListComponent implements OnInit {
  posts = signal<BlogData['posts']>([]);
  loading = signal(true);
  error = signal<string | null>(null);

  async ngOnInit() {
    await this.loadBlogPosts();
  }

  private async loadBlogPosts() {
    this.loading.set(true);
    this.error.set(null);
    
    try {
      /* Retrieve blog posts from JSON file */
      const response = await fetch('blog-posts.json', { cache: 'no-cache' });
      if (!response.ok) throw new Error(`❌ HTTP ERROR ${response.status}`);
      const blogData: BlogData = await response.json();
      
      /* Filter for published posts & sort by ID number */
      const publishedPosts = blogData.posts
        .filter(post => post.published)
        .sort((a, b) => {
          return parseInt(b.id) - parseInt(a.id); /* Sort in descending order (..., 3, 2, 1) */
        });
      
      /* Updates the posts signal with published posts */
      this.posts.set(publishedPosts);
    } catch (e: any) {
      this.error.set(e.message || '❌ Failed to load blog posts');
    } finally {
      this.loading.set(false);
    }
  }
}
